### ISSUE TITLE
Support editors

### ISSUE THREAD

**Issue by eGavr** [bemhint/bemhint#54]
- [ ] sublime
- [ ] vim
- [ ] idea ?

**Comment by blond** [comment]
+ [atom](https://atom.io/) ;)

**Comment by zxqfox** [comment]
Guys, зачем? Не надо делать интеграцию. Сделайте нормальное js/cli api.

**Comment by blond** [comment]
@zxqfox одно другому не мешает. 

Я вот пользуюсь [linter-jscs](https://atom.io/packages/) на сохранение файла. Удобно это тем, что не нужно искать из консоли код в котором что-то не так.

**Comment by blond** [comment]
@eGavr для интеграции с IDE линтеры должны уметь указывать на строку с ошибкой, а не просто выводить ошибку.

**Comment by zxqfox** [comment]
@blond Что делать тем, кто не пользуется редакторами на JS? Писать плагины на Java/Python?

**Comment by blond** [comment]
> Что делать тем, кто не пользуется редакторами на JS?

У них будет выбор или использовать CLI, или писать плагины :)

**Comment by eGavr** [comment]
Кажется, что в любом случае плагины для редакторов – это не код `bemhint`-а, кому необходимо, тот реализует как отдельный плагин для редактора.
