### ISSUE TITLE
Missing error.location definition in README

### ISSUE THREAD

**Issue by Vittly** [bemhint/bemhint#78]
Should add `* location {Object} – ...` about [location feature](https://github.com/bemhint/bemhint/commit/415818ec72d5091471883daf38415d6697905cf5#diff-5448512eca99ec28596c2d13aee50a57R92) into README (my bad).

**Comment by eGavr** [comment]
Mk a PR ?

**Comment by Vittly** [comment]
resolving in https://github.com/bemhint/bemhint/pull/80
