### ISSUE TITLE
Improve the configuration file

### ISSUE THREAD

**Issue by dima117** [bemhint/bemhint#81]
Need to add the ability to specify the same plugin several times in the configuration with different parameters. I suggest changing the format of the `plugins` configuration section: `object` to `array`.

Also it would be good to define several named sets of settings (profiles) and run the bemhint by specifying the name of the desired profile.

**Comment by Vittly** [comment]
Examples? Before/after?

**Comment by Vittly** [comment]
May be one example of configuration bemhint-deps-schema with standard schema and several custom schemas?

**Comment by dima117** [comment]
## Example

Before:

```js
module.exports = {
    levels: [ ... ],

    plugins: {
        // plugin is enabled
        '<plugin_name_1>':  true,

        // plugin is enabled and uses following settigns
        '<plugin_name_2>': { ... }, 
        ...
    }
};
```

After:

```js
module.exports = {
    levels: [ ... ],

    plugins: [
        // plugin is enabled
        { 
            name:  '<plugin_name_1>' 
        },

        // plugin is enabled and uses following settigns
        { 
            name:  '<plugin_name_2>', 
            .... 
        }
    ]
};
```

**Comment by eGavr** [comment]
Fixed in https://github.com/bemhint/bemhint/pull/85
